# This workflow activates every time a Pull-Request its open or reopened
# This workflow keeps commits from having quality issues, test and build failures.

name: PR Analyzer

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  lint-analyzer:
    name: Lint Flutter Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - name: Analyze Flutter
        uses: ValentinVignal/action-dart-analyze@v0.12
        with:
          fail-on: "info"

  unit-test:
    name: Unit Test Job
    needs: [lint-analyzer]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test test/unit_test --coverage
      - uses: codecov/codecov-action@v2

  ui-test:
    name: UI Test Job
    needs: [lint-analyzer]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test test/ui_test  --coverage
      - uses: codecov/codecov-action@v2

  integration-test:
    name: Integration Test Job
    needs: [lint-analyzer]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test test/integration_test --coverage
      - uses: codecov/codecov-action@v2

  android-build:
    name: Build app (Android)
    needs: [unit-test, ui-test, integration-test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle

  web-build:
    name: Build app (Web)
    needs: [unit-test, ui-test, integration-test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web
