# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Test and Builds flutter project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Loading dependencies...
      - run: flutter pub get
      - name: Analyzing project
      - run: flutter analyze
      - name: Running test
      - run: flutter test
      - name: Building flutter web app
      - run: flutter build web
