# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  
  workflow_dispatch:
  
    

jobs:
  build:
      name: Test and Builds flutter project
      runs-on: ubuntu-latest

      steps:
        - uses: subosito/flutter-action@v2.3.0
        
        - name: Flutter analysis
        - run: flutter analyze
        
        - name: Flutter test
        - run: flutter test
                        
        - name: Flutter build
        - run: flutter build web
        
          
      

