# This workflow activates every time a Pull-Request its open or reopened
# This workflow keeps commits from having quality issues, test and build failures.

name: PR Analyzer

on:
  pull_request:

jobs:
  analyzer:
    name: Lint Flutter Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      # - run: flutter analyze
      - name: Analyze Flutter
        uses: ValentinVignal/action-dart-analyze@v0.12
        with:
          fail-on: "info"

  unit_test:
    name: Unit Test Job
    needs: [analyzer]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test test/unit_test

  ui_test:
    name: UI Test Job
    needs: [analyzer]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test test/ui_test

  integration_test:
    name: Integration Test Job
    needs: [analyzer]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test test/integration_test

  android-build:
    name: Build app (Android)
    needs: [unit_test, ui_test, integration_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle

  web-build:
    name: Build app (Web)
    needs: [unit_test, ui_test, integration_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web
